### ISSUE TITLE
aws-iamctl is not working with python >= 3.10 - "ImportError: cannot import name 'Mapping' from 'collections'"

### ISSUE THREAD

**Issue by DutchForeigner** [aws-samples/aws-iamctl#6]
aws-iamctl does not work with python >= 3.10
You would get an error when running 'iamctl': "ImportError: cannot import name 'Mapping' from 'collections'"
This seems to be a known issue with 'collections' and python >=3.10

- https://stackoverflow.com/questions/69381312/in-vs-code-importerror-cannot-import-name-mapping-from-collections
- https://stackoverflow.com/a/69727802/13994294.

You can make it to work, by updating some of the module versions in 'requirements.txt'
Updating to below versions worked for me:
boto3==1.26.60
botocore=1.29.60
s3transfer==0.6.0
urllib3==1.26.14

**Comment by BogdanSorlea** [comment]
@DutchForeigner you also need to update `setup.py` given the current version of the code
